services:
  server:
    container_name: ${BACKEND_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    tty: true
    depends_on:
      - postgres
      - redis
    volumes:
      - ./apps/api:/app
      - /etc/localtime:/etc/localtime:ro # タイムゾーンを日本時刻に設定
    ports:
      - ${BACKEND_PORT}:${BACKEND_CONTAINER_PORT}
    security_opt:
      - seccomp:unconfined
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - OAUTH_CALLBACK_URL=${OAUTH_CALLBACK_URL}
      - "TZ=Asia/Tokyo" # タイムゾーンを日本時刻に設定

  postgres:
    container_name: ${POSTGRES_HOST}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - "TZ=Asia/Tokyo" # タイムゾーンを日本時刻に設定
    image: postgres:18.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d  #initial data
    ports:
      - ${POSTGRES_PORT}:5432

  redis:
    container_name: ${REDIS_HOST}
    image: redis:8.4-alpine
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  postgres_data:
  redis_data: